version: '3'
services:
  php:
    build: ./docker/php/
    environment:
      TIMEZONE: Europe/Chisinau
      PHP_IDE_CONFIG: "serverName=sf4.loc"
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./app:/var/www/app
    working_dir: /var/www/app
    ports:
      - 9001:9000

  nginx:
    image: nginx:1.11
    depends_on:
      - php
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/var/www/app
    ports:
      - 8080:80

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app